import Head from 'next/head'
import React from 'react'

function Blog() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>This is a slug blog</div>
    </>
  )
}

export default Blog
