/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import React from 'react'

function Contact() {
  return (
    <>
      <Head>
        <title>Contact me!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="to-violet-5000 flex h-screen items-center justify-center overflow-hidden bg-gradient-to-t from-blue-500 to-gray-200">
        <img src="/contact.jpg" alt="" className="w-[320px] object-contain" />
      </div>
    </>
  )
}

export default Contact
