/* eslint-disable @next/next/no-img-element */
import { GetServerSideProps, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { urlFor } from '../sanity'
import fetchProjects from '../utils/fetchProjects'

interface Props {
  projects: Project[]
}

function Projects({ projects }: Props) {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-[rgb(36,36,36)]">
        <div className="mx-auto max-w-6xl space-y-10 py-10">
          <h1 className="text-center text-2xl tracking-[20px] text-gray-500 lg:text-3xl">
            My Projects
          </h1>

          <div className="grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-3 px-8 md:px-0">
            {projects.map((project, index) => (
              <a key={index} href={project.linkToBuild}>
                <div className="cursor-pointer rounded-2xl duration-200 ease-in-out hover:scale-105">
                  <img
                    src={urlFor(project.image).url()}
                    alt=""
                    className="min-h-[240px] w-full rounded-tl-2xl rounded-tr-2xl object-cover"
                  />
                  <div className="rounded-bl-2xl rounded-br-2xl bg-white p-4 text-center text-2xl font-semibold text-black space-y-4">
                    <div className="flex items-center justify-center gap-x-4">
                      {project.technologies.map((technology, index) => (
                        <img
                          src={urlFor(technology.image).url()}
                          alt=""
                          key={index}
                          className="h-10 w-10 rounded-full object-cover"
                        />
                      ))}
                    </div>
                    <h1>{project.title}</h1>
                  </div>
                </div>
              </a>
            ))}
          </div>
        </div>
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const projects = await fetchProjects()
  return {
    props: {
      projects,
    },
  }
}

export default Projects
