import Head from 'next/head'
import React from 'react'

function Blogs() {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto mb-8 max-w-7xl px-10">
        <div className="grid grid-cols-12 gap-12 lg:grid-cols-1">
          {/* Posts */}
          <div className="col-span-1 lg:col-span-8"></div>
          {/* Widget */}
          <div className="col-span-1 lg:col-span-4">
            <div className='relative lg:sticky top-8'></div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Blogs
