import styles from '../../styles/blogs.module.css'
import Head from 'next/head'
import React from 'react'
import { Categories, Header, PostCard, Widget } from '../../components/Blogs'
import { GetStaticProps } from 'next'
import axios from 'axios'
import fetchPosts from '../../utils/fetchPosts'

interface Props {
  posts: Post[]
}

function Blogs({ posts }: Props) {
  console.log(posts)

  return (
    <div className={`${styles.blogs}`}>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto mb-8 max-w-7xl space-y-8 px-10">
        <Header />
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-12">
          {/* Posts */}
          <div className="col-span-1 lg:col-span-8">
            {posts.map((post, index) => (
              <PostCard key={index} post={post} />
            ))}
          </div>
          {/* Widget */}
          <div className="col-span-1 lg:col-span-4 sticky top-8">
            <div className="">
              <Widget />
              <Categories />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const posts = await fetchPosts()

  return {
    props: {
      posts,
    },
  }
}

export default Blogs
